title: Git Wiki Team 1
description: A starter template for publishing a website to GitHub pages using Jekyll, Just the Docs, and GitHub Actions.
theme: just-the-docs

url: https://JohnAllAlong.github.io/Just-The-Docs-Team-1-Fork

aux_links:
  Template Repository: https://github.com/JohnAllAlong/Just-The-Docs-Team-1-Fork
